### ISSUE TITLE
`IndexError: Invalid index: 3 with size 3.` with example code from Shading-and-error-bars

### ISSUE THREAD

**Issue by gepcel** [lukelbd/proplot#243] opened 2021-01-21 12:54 UTC
Example code in section [Shading-and-error-bars](https://proplot.readthedocs.io/en/latest/1dplots.html#Shading-and-error-bars) of the document raises `IndexError: Invalid index: 3 with size 3.` error, with proplot v0.6.4 and matplotlib v3.3.2 .

Post the example code and error message here.

Example code:

```
import proplot as plot
import numpy as np
import pandas as pd
plot.rc['title.loc'] = 'uc'

# Generate sample data
state = np.random.RandomState(51423)
data = state.rand(20, 8).cumsum(axis=0).cumsum(axis=1)[:, ::-1]
data = data + 20 * state.normal(size=(20, 8)) + 30
data = pd.DataFrame(data, columns=np.arange(0, 16, 2))
data.name = 'variable'

# Generate figure
fig, axs = plot.subplots(
    nrows=3, aspect=1.5, axwidth=4,
    share=0, hratios=(2, 1, 1)
)
axs.format(suptitle='Indicating error bounds with various plotting commands')
axs[1:].format(xlabel='column number', xticks=1, xgrid=False)

# Automatically calculate medians and display default percentile range
ax = axs[0]
obj = ax.barh(
    data,
    color='light red', legend=True,
    medians=True, boxpctiles=True, barpctiles=(5, 95),
)
ax.format(title='Column statistics')
ax.format(ylabel='column number', title='Bar plot', ygrid=False)

# Automatically calculate means and display requested standard deviation range
ax = axs[1]
ax.scatter(
    data,
    color='denim', marker='x', markersize=8**2, linewidth=0.8,
    means=True, shadestds=(-1, 1), shadelabel=True, legend='ll',
)
ax.format(title='Scatter plot')

# Manually supply error bar data and legend labels
ax = axs[2]
means = data.mean(axis=0)
means.name = data.name
shadedata = np.percentile(data, (25, 75), axis=0)  # dark shading
fadedata = np.percentile(data, (5, 95), axis=0)  # light shading
ax.plot(
    means,
    shadedata=shadedata, fadedata=fadedata,
    shadelabel='50% CI', fadelabel='90% CI',
    color='ocean blue', barzorder=0, boxmarker=False, legend='ll',
)
ax.format(title='Line plot')
plot.rc.reset()
```

Error message is like:

```
Error in callback <function install_repl_displayhook.<locals>.post_execute at 0x000002FCFC4AAD38> (for post_execute):
C:\anaconda3\lib\site-packages\proplot\figure.py:1044: ProPlotWarning: Using "fig.add_subplot()" with ProPlot figures may result in unexpected behavior. Please use "proplot.subplots()" instead.
Traceback (most recent call last):

  File "C:\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 138, in post_execute
    draw_all()

  File "C:\anaconda3\lib\site-packages\matplotlib\_pylab_helpers.py", line 138, in draw_all
    manager.canvas.draw_idle()

  File "C:\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2012, in draw_idle
    self.draw(*args, **kwargs)

  File "C:\anaconda3\lib\site-packages\proplot\figure.py", line 94, in _preprocess
    result = func(self, *args, **kwargs)

  File "C:\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)

  File "C:\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\anaconda3\lib\site-packages\matplotlib\figure.py", line 1854, in draw
    self.execute_constrained_layout(renderer)

  File "C:\anaconda3\lib\site-packages\matplotlib\figure.py", line 2566, in execute_constrained_layout
    do_constrained_layout(fig, renderer, h_pad, w_pad, hspace, wspace)

  File "C:\anaconda3\lib\site-packages\matplotlib\_constrained_layout.py", line 148, in do_constrained_layout
    _make_ghost_gridspec_slots(fig, gs)

  File "C:\anaconda3\lib\site-packages\matplotlib\_constrained_layout.py", line 248, in _make_ghost_gridspec_slots
    ax = fig.add_subplot(gs[nn])

  File "C:\anaconda3\lib\site-packages\proplot\gridspec.py", line 402, in __getitem__
    num1, num2 = self._normalize(key, nrows_active * ncols_active)

  File "C:\anaconda3\lib\site-packages\proplot\gridspec.py", line 440, in _normalize
    raise IndexError(f'Invalid index: {key} with size {size}.')

IndexError: Invalid index: 3 with size 3.

C:\anaconda3\lib\site-packages\proplot\figure.py:1047: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  return super().add_subplot(*args, **kwargs)
Traceback (most recent call last):

  File "C:\anaconda3\lib\site-packages\IPython\core\formatters.py", line 341, in __call__
    return printer(obj)

  File "C:\anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 250, in <lambda>
    png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

  File "C:\anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 140, in retina_figure
    pngdata = print_figure(fig, fmt='retina', **kwargs)

  File "C:\anaconda3\lib\site-packages\IPython\core\pylabtools.py", line 132, in print_figure
    fig.canvas.print_figure(bytes_io, **kw)

  File "C:\anaconda3\lib\site-packages\proplot\figure.py", line 94, in _preprocess
    result = func(self, *args, **kwargs)

  File "C:\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2217, in print_figure
    **kwargs)

  File "C:\anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)

  File "C:\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)

  File "C:\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py", line 407, in draw
    self.figure.draw(self.renderer)

  File "C:\anaconda3\lib\site-packages\matplotlib\artist.py", line 41, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "C:\anaconda3\lib\site-packages\matplotlib\figure.py", line 1854, in draw
    self.execute_constrained_layout(renderer)

  File "C:\anaconda3\lib\site-packages\matplotlib\figure.py", line 2566, in execute_constrained_layout
    do_constrained_layout(fig, renderer, h_pad, w_pad, hspace, wspace)

  File "C:\anaconda3\lib\site-packages\matplotlib\_constrained_layout.py", line 148, in do_constrained_layout
    _make_ghost_gridspec_slots(fig, gs)

  File "C:\anaconda3\lib\site-packages\matplotlib\_constrained_layout.py", line 248, in _make_ghost_gridspec_slots
    ax = fig.add_subplot(gs[nn])

  File "C:\anaconda3\lib\site-packages\proplot\gridspec.py", line 402, in __getitem__
    num1, num2 = self._normalize(key, nrows_active * ncols_active)

  File "C:\anaconda3\lib\site-packages\proplot\gridspec.py", line 440, in _normalize
    raise IndexError(f'Invalid index: {key} with size {size}.')

IndexError: Invalid index: 3 with size 3.

<Figure size 467.092x715.253 with 6 Axes>
```

**Comment by pratiman-91** [comment] 2021-03-23 03:13
I am unable to reproduce this error. Not sure what's wrong.

**Comment by lukelbd** [comment] 2021-06-30 11:52
Not sure what the issue is either -- I tried this with a few different matplotlib versions and couldn't reproduce it. Interesting traceback though. Closing for now but let me know if you're still having this issue and I'll reopen.

**Closed by lukelbd** 2021-06-30 11:52 UTC
