### ISSUE TITLE
Pass rc.cmap and rc.cycle arguments through respective constructor functions

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#169] opened 2020-05-16 12:11 UTC
### Description

Since `cycle` supports cmaps, the input of cmap name in the configuration should be supported.

### Steps to reproduce

```python
import proplot as plot
import numpy as np

fig, axs = plot.subplots()
state = np.random.RandomState(51423)
data = (20 * state.rand(10, 21) - 10).cumsum(axis=0)

plot.rc.update({'cycle': 'plum', 'lines.linewidth': '5'})
lines = axs.plot(data[:, :5])
```

**Expected behavior**:
Like:
```
plot.rc.update({'lines.linewidth': '5'})
lines = axs.plot(data[:, :5], cycle='plum')
```

![cmap](https://user-images.githubusercontent.com/30388627/82119436-1e34be00-97b1-11ea-9e1c-b73bba801e3c.png)

**Actual behavior**: [What actually happened]
```
Traceback (most recent call last):
  File "/home/xin/Desktop/test.py", line 11, in <module>
    plot.rc.update({'cycle': 'plum', 'lines.linewidth': '5'})
  File "/home/xin/Documents/Github/proplot/proplot/config.py", line 906, in update
    self.__setitem__(prefix + key, value)
  File "/home/xin/Documents/Github/proplot/proplot/config.py", line 410, in __setitem__
    kw_quick, kw_added, kw_params = self._get_param_dicts(key, value)
  File "/home/xin/Documents/Github/proplot/proplot/config.py", line 490, in _get_param_dicts
    colors = _get_cycle_colors(value)
  File "/home/xin/Documents/Github/proplot/proplot/config.py", line 1020, in _get_cycle_colors
    + ', '.join(map(repr, cycles)) + '.'
ValueError: Invalid cycle name 'plum'. Options are: '538', 'accent', 'classic', 'colorblind', 'colorblind10', 'dark2', 'default', 'flatui', 'ggplot', 'paired', 'pastel1', 'pastel2', 'qual1', 'qual2', 'set1', 'set2', 'set3', 'tab10', 'tab20', 'tab20b', 'tab20c'.
```

### Proplot version
[master branch](https://github.com/lukelbd/proplot/commit/6903e33efe963192ce465a51341502714c812c58)

**Comment by lukelbd** [comment] 2021-07-30 20:34
I'm going to close this as a duplicate of #69. When I add rc-param assignment validation it will be trivial to pass assignments to `rc.cmap` and `rc.cycle` through the `Colormap` and `Cycle` constructors.

**Closed by lukelbd** 2021-07-30 20:34 UTC
Labels: feature

**Comment by lukelbd** [comment] 2021-08-18 19:36
Since rc settings are now validated this is now implemented. It works by saving the colormap name to the settings (necessary since the rc dicts should only contain settings printable to `proplotrc` files). For example: 

```python
pplt.rc.cmap = pplt.Colormap('magma')
print(pplt.rc.cmap)
```

returns `'magma'` rather than a colormap instance. This is ok since colormaps assigned to these settings are also automatically registered.
