### ISSUE TITLE
Subplot title causes error in position of suptitle

### ISSUE THREAD

**Issue by bradyrx** [lukelbd/proplot#6] opened 2019-01-28 20:34 UTC
If one generates both a suptitle and a subplot title for the uppermost subplot, the suptitle gets pulled down into the plot and is hard to read (especially with subscripts are used in it).

With subplot title:
<img width="560" alt="screen shot 2019-01-28 at 1 31 48 pm" src="https://user-images.githubusercontent.com/8881170/51864481-170a4800-2301-11e9-83a2-89bb0e0ebeec.png">

Without subplot title:
<img width="556" alt="screen shot 2019-01-28 at 1 32 24 pm" src="https://user-images.githubusercontent.com/8881170/51864504-2c7f7200-2301-11e9-8fd2-4d7974a7caea.png">

Code:
```python
import numpy as np
import proplot as plot
def _rand_series(N):
    return np.random.rand(N,) + np.linspace(0, 0.5, N)

d1, d2 = _rand_series(100), _rand_series(100)
f, ax = plot.subplots(nrows=2, axwidth=6, aspect=5)
p1 = ax[0].plot(d1, color='r')
p2 = ax[1].plot(d2, color='sea')
#ax[0].format(title='interior title', titlepos='ri')
ax.format(ylim=[0, 1.5], suptitle='sup title', small=14, large=18)
```

Note that if you uncomment the line and do `ax[1].format(title='foo')`, the suptitle is fine. The error only occurs if it's the subplot directly interacting with the suptitle.

**Comment by lukelbd** [comment] 2019-01-31 23:46
Interesting -- pretty sure I know what the problem is already. By default I have the "super title" position set to one line above the "title" position for titles on the top row of axes (proplot's version of the "super title" is different from the matplotlib version -- I center it between the left edge of the lefmost axes and the right edge of the rightmost axes, and vertically position it relative to the axes rather than relative to the figure edge). I guess I didn't check for interior-positioned titles. Should be a simple fix.

**Comment by lukelbd** [comment] 2019-02-28 02:03
Ok it's fixed now. Here's without the inner title: 

![bug1](https://user-images.githubusercontent.com/19657652/53535999-dea58780-3ac1-11e9-9b10-b1b8f74d3f56.png)

And here's with the inner title:

![bug2](https://user-images.githubusercontent.com/19657652/53536000-dea58780-3ac1-11e9-96f3-35898c19d8b9.png)

P.S. I added the `.proplotrc` feature! You can read about it [here](https://lukelbd.github.io/proplot/rcmod.html#proplotrc-file).

**Closed by lukelbd** 2019-02-28 02:03 UTC
