### ISSUE TITLE
Error in some geographic plots

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#267] opened 2021-08-05 21:26 UTC
### Description

Some basic geographic plots cannot be plotted with proplot 0.7.

Originally, I found that some values are not covered by the automatic colorbar levels in geographic plots. Some large values are not colored unless `vmin` and `vmax` are explicitly defined. I couldn't reproduce this error in a simple example but I guess it's related to this issue as we can see from the error message.

### Steps to reproduce

```python
import xarray as xr
import proplot as pplt

ds = xr.tutorial.open_dataset('air_temperature').load()

fig, ax = pplt.subplots(proj='cyl')
#fig, ax = pplt.subplots(proj='eqearth') # This works
ax.format(coast=True)
ax.contourf(ds.isel(time=0)['air'])
```

**Actual behavior**: [What actually happened]
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-92d29737d5eb> in <module>
      6 fig, ax = pplt.subplots(proj='cyl')
      7 ax.format(coast=True)
----> 8 ax.contourf(ds.isel(time=0)['air'])

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/ui.py in _iterator(*args, **kwargs)
    780                 result = []
    781                 for func in objs:
--> 782                     result.append(func(*args, **kwargs))
    783                 if len(self) == 1:
    784                     return result[0]

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in <lambda>(self, _func, _method, *args, **kwargs)
   4468         method = functools.wraps(method)(
   4469             lambda self, *args, _func=func, _method=method, **kwargs:
-> 4470             _func(self, *args, _method=_method, **kwargs)
   4471         )
   4472 

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in default_transform(self, transform, *args, **kwargs)
    521     if transform is None:
    522         transform = PlateCarree()
--> 523     return method(self, *args, transform=transform, **kwargs)
    524 
    525 

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in <lambda>(self, _func, _method, *args, **kwargs)
   4468         method = functools.wraps(method)(
   4469             lambda self, *args, _func=func, _method=method, **kwargs:
-> 4470             _func(self, *args, _method=_method, **kwargs)
   4471         )
   4472 

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in standardize_2d(self, data, autoformat, order, globe, *args, **kwargs)
   1270 
   1271     # Call function
-> 1272     return method(self, x, y, *zs, **kwargs)
   1273 
   1274 

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in <lambda>(self, _func, _method, *args, **kwargs)
   4468         method = functools.wraps(method)(
   4469             lambda self, *args, _func=func, _method=method, **kwargs:
-> 4470             _func(self, *args, _method=_method, **kwargs)
   4471         )
   4472 

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/internals/warnings.py in deprecate_kwargs(*args, **kwargs)
    102                     'removed in the next major release. Please use {key_new!r} instead.'
    103                 )
--> 104             return func_orig(*args, **kwargs)
    105         return deprecate_kwargs
    106     return decorator

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in apply_cmap(self, cmap, cmap_kw, norm, norm_kw, extend, levels, N, values, vmin, vmax, locator, locator_kw, symmetric, positive, negative, nozero, discrete, edgefix, labels, labels_kw, fmt, precision, inbounds, colorbar, colorbar_kw, *args, **kwargs)
   3478     else:
   3479         kw.update(levels=levels, values=values, cmap=cmap, minlength=2 - int(contour))
-> 3480         norm, cmap, levels, ticks = _build_discrete_norm(self, *args, **kw)
   3481 
   3482     # Call function with correct keyword args

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in _build_discrete_norm(self, levels, values, cmap, norm, norm_kw, extend, vmin, vmax, minlength, *args, **kwargs)
   3158     else:
   3159         # Determine levels automatically
-> 3160         levels, locator = _auto_levels_locator(
   3161             self, *args, N=levels, norm=norm, vmin=vmin, vmax=vmax, extend=extend, **kwargs  # noqa: E501
   3162         )

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/proplot/axes/plot.py in _auto_levels_locator(self, N, norm, norm_kw, extend, vmin, vmax, locator, locator_kw, symmetric, positive, negative, nozero, inbounds, centers, counts, *args)
   2962                 z = ma.masked_invalid(z, copy=False)
   2963                 if automin:
-> 2964                     vmin = float(z.min())
   2965                 if automax:
   2966                     vmax = float(z.max())

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/numpy/ma/core.py in min(self, axis, out, fill_value, keepdims)
   5698         # No explicit output
   5699         if out is None:
-> 5700             result = self.filled(fill_value).min(
   5701                 axis=axis, out=out, **kwargs).view(type(self))
   5702             if result.ndim:

~/miniconda3/envs/basicf4/lib/python3.8/site-packages/numpy/core/_methods.py in _amin(a, axis, out, keepdims, initial, where)
     42 def _amin(a, axis=None, out=None, keepdims=False,
     43           initial=_NoValue, where=True):
---> 44     return umr_minimum(a, axis, None, out, keepdims, initial, where)
     45 
     46 def _sum(a, axis=None, dtype=None, out=None, keepdims=False,

ValueError: zero-size array to reduction operation minimum which has no identity
```

### Proplot version
matplotlib 3.3.4
proplot 0.7.0

**Comment by lukelbd** [comment] 2021-08-18 20:44
This is now fixed on master (son to be v0.8). Looks like the bug was caused by an empty array passed to the vmin/vmax scaling function. On master that algorithm is majorly cleaned up -- tried your example and it works just fine.

**Closed by lukelbd** 2021-08-18 20:44 UTC
