### ISSUE TITLE
sharex, sharey do not work for geographic plot

### ISSUE THREAD

**Issue by kinyatoride** [lukelbd/proplot#199] opened 2020-06-26 15:12 UTC
### Description

Changing the parameters of sharex, sharey do not work for geographic plot.
Thanks always.

### Steps to reproduce

```python
import proplot as plot

fig, axs = plot.subplots(ncols=2, nrows=2, proj='cyl', share=3)
axs.format(coast=True, labels=True)
```

**Actual behavior**: [What actually happened]
![Screen Shot 2020-06-26 at 8 09 27](https://user-images.githubusercontent.com/61028484/85872268-5c47d900-b784-11ea-8a85-c22ec999e06b.png)

### Equivalent steps in matplotlib

```python
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter

fig, axes = plt.subplots(2, 2, sharex=True, sharey=True,
                subplot_kw=dict(projection=ccrs.PlateCarree()))

xticks = np.linspace(-180, 180, 7)
yticks = np.linspace(-90, 90, 7)
for ax in axes.flat:
    ax.coastlines()
    ax.gridlines(xlocs=xticks, ylocs=yticks, linestyle='--', alpha=0.5)
    ax.set_xticks(xticks, crs=ccrs.PlateCarree())
    ax.set_yticks(yticks, crs=ccrs.PlateCarree())
    ax.xaxis.set_major_formatter(LongitudeFormatter(zero_direction_label=True))
    ax.yaxis.set_major_formatter(LatitudeFormatter())
```
![Screen Shot 2020-06-26 at 8 09 06](https://user-images.githubusercontent.com/61028484/85872215-4f2aea00-b784-11ea-9aa0-0cf35e203b19.png)

### Proplot version

0.6.4

**Comment by lukelbd** [comment] 2020-06-26 15:22
Duplicate of: #79 (see also #183)

**Closed by lukelbd** 2020-06-26 15:22 UTC
