### ISSUE TITLE
How to apply spany to dual axes?

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#319] opened 2022-01-07 21:37 UTC
### Description

I wanna only to show the label of rightest dual y-axis.

### Steps to reproduce

```python
import proplot as pplt

fig, axs = pplt.subplots(nrows=3, ncols=3, spany=0)

axs.format(
    xformatter='null', ylabel='pressure (hPa)',
    ylim=(1000, 100), xlocator=[],
)

axs.dualy(
    'height', label='Height (km)', ticks=2.5
)
```

**Expected behavior**: [What you expected to happen]
![image](https://user-images.githubusercontent.com/30388627/148610429-babf0aaa-1bd0-410d-b488-cc5a14abcdee.png)

I can make this work by setting something manually. Is there a better method?
Is it better to apply spany to both yaxis and dual yaxis?
```
axs_dual = axs.dualy('height', label='', ticks=2.5)
for ax in[axs_dual[2], axs_dual[5], axs_dual[8]]:
    ax.format(ylabel='Height (km)')
```

**Actual behavior**: [What actually happened]
![image](https://user-images.githubusercontent.com/30388627/148610458-c8a4b8d3-0716-4e0c-b05e-707925346af8.png)

### Proplot version

Paste the results of `import matplotlib; print(matplotlib.__version__); import proplot; print(proplot.version)`here.
```
3.5.1
0.9.5.post105
```

**Comment by lukelbd** [comment] 2022-01-13 22:48
I think this is a duplicate of #205.

When I finally implement this, I will also support sharing and spanning for ylabels on the right side and xlabels on the top side even without dual axes. Currently, proplot only supports left and bottom labels, which is arbitrary/annoying.

**Closed by lukelbd** 2022-01-13 22:48 UTC
