### ISSUE TITLE
Issues with popup qtagg and tkagg backends

### ISSUE THREAD

**Issue by Xunius** [lukelbd/proplot#244] opened 2021-02-10 12:58 UTC
### Description

Trying to create a basic `contourf()`. The figure window shows up, but it is shaking, and Python freezes.

It seems like `proplot` is adjusting sizes or something but ends up in an infinite loop. 

### Steps to reproduce

Installed `proplot` using `conda install -c conda-forge proplot`.
Then run this following script:

```python
import numpy as np
import proplot as pplot

if __name__=='__main__':

    lons=np.arange(0, 360)
    lats=np.arange(-90, 90)
    lons, lats=np.meshgrid(lons, lats)
    var=np.random.random(lons.shape)

    fig,ax=pplot.subplots()
    cs=ax.contourf(lons, lats, var)
    ax.format(title='Test')
    ax.colorbar(cs)
    fig.show()

```

**Expected behavior**: A window pops up showing a global mean sea level pressure plot.

**Actual behavior**: A window pops up but the figure elements and the figure window itself are shaking. Python freezes.

I also created a screencapture showing the issue: https://github.com/Xunius/git_demo/blob/master/simplescreenrecorder-2021-02-10_20.33.19.mp4 (**NOTE** the example in the screencatpure is using cartopy, but the symptom is the same.)

### Equivalent steps in matplotlib

Pretty sure this is `proplot` specific.

### Proplot version

* Proplot: 0.6.4
* Python: 3.8.5
* matplotlib: 3.3.2

The issue also happens in another environment:

* Proplot: 0.6.4
* Python: 3.7.9
* matplotlib: 3.2.2

OS: Manjaro Linux

**Comment by lukelbd** [comment] 2021-06-30 11:55
Which backend are you using? Try printing `from matplotlib import rcParams; print(rcParams['backend'])` from your matplotilb session.

Proplot struggles with a lot of "interactive" backends because its geometry algorithm automatically resizes figures (which can trigger a backend refresh, which can trigger a figure resize... have to work around these issues carefully).

**Comment by Xunius** [comment] 2021-07-01 02:39
I was using Qt5Agg, and I tried TkAgg which is also unstable.

**Comment by lukelbd** [comment] 2021-07-01 06:15
Thanks. Just tried it out in an ipython session with `%matplotlib qt` and I also get very slow/laggy behavior. These are always fun to debug...

For now if you're on mac you can also try `%matplotlib osx`, seems to work fine for me. And proplot usually works really well with static inline jupyter notebook/console backends.

**Comment by Xunius** [comment] 2021-07-01 07:35
Thanks for replying. I'm afraid I don't have a mac machine. Most of the time I don't use ipython or jupyter, but plain python in a terminal. By "static inline console backends" did you mean backends like`PS`, `Agg`, `PDF`? With these I can only save the image to a file, but can't display it in a window using `figure.show()`, can I?

**Comment by lukelbd** [comment] 2021-07-01 18:39
> By "static inline console backends" did you mean...

I meant backends used in jupyter notebooks and consoles. Looks something like this:

<img width="1341" alt="Screen Shot 2021-07-01 at 12 31 53 PM" src="https://user-images.githubusercontent.com/19657652/124173484-52784600-da68-11eb-9b82-887dc1b27e62.png">

<img width="1323" alt="Screen Shot 2021-07-01 at 12 38 13 PM" src="https://user-images.githubusercontent.com/19657652/124174121-3628d900-da69-11eb-9626-bff0031ea43f.png">

> Most of the time I don't use ipython or jupyter, but plain python in a terminal.

Will try to get on this, proplot should definitely work with the basic popup backends used when running naked python scripts.

**Comment by lukelbd** [comment] 2021-07-04 19:31
Hmmm, I can't reproduce this behavior anymore... Initially thought it was maybe fixed by #235 but tried the qt5agg and tkagg backends in v0.6.4 and they seems to work fine too. Could you re-upload the movie? Looks like the link is dead.

I wonder if this could be platform-specific. Maybe your OS is for some reason automatically resizing the window slightly (or were you maybe trying to manually resize the figure by clicking and dragging)? When the window changes size, proplot tries to adjust the spacing, and for figures with dense graphics (like your example) this is always going to be pretty slow. A workaround would be to use `fig.subplots(..., tight=False)` and set spaces manually but that's obviously not ideal.

Submitting a release really soon, so I think if we can reproduce+fix this it will have to wait until the next minor release.

**Comment by Xunius** [comment] 2021-07-05 11:23
I forgot to make the repo where the video was uploaded to public. Could you try that link again and see if you can see the video?

Setting the `tight=False` kwarg does solve the shaking window problem, but the colorbar is put too far away. I assume that wouldn't be a viable workaround.

**Comment by lukelbd** [comment] 2021-07-05 19:21
Wow that is... interesting. Yeah with `tight=False` you'd have to manually set all your spacings -- for the colorbar spacing you would use e.g. `ax.colorbar(..., space='2em')`, `ax.colorbar(..., space=0.5)`, etc (see [this page](https://proplot.readthedocs.io/en/latest/why.html#physical-units-engine)).

Unfortunately it looks like this is probably OS specific so will be hard for me to debug but I'll take a close look at the auto spacing algorithm. Interesting that this happens with both `Qt5Agg` and `TkAgg`.

And just to confirm, this doesn't happen with matplotlib plots? Example:

```python
import matplotlib.pyplot as plt
import numpy as np

if __name__=='__main__':

    lons=np.arange(0, 360)
    lats=np.arange(-90, 90)
    lons, lats=np.meshgrid(lons, lats)
    var=np.random.random(lons.shape)

    fig,ax=plt.subplots()
    cs=ax.contourf(lons, lats, var)
    ax.set_title('Test')
    fig.colorbar(cs)
    fig.show()
```

**Comment by Xunius** [comment] 2021-07-06 01:03
Yes I can confirm that this doesn't happen to plain matplotlib plot with tight_layout on.

**Comment by lukelbd** [comment] 2021-07-12 02:35
FYI was able to reproduce this, but strangely, only for plots with certain content (e.g. everything was fine with 1 `pcolor` subplot and one empty subplot, but not 2 `pcolor` subplots).

Definitely on my radar but will probably take a deep dive into my whole auto sizing algorithm to figure out. Maybe 0.7.1

**Comment by Xunius** [comment] 2021-07-12 04:19
Thanks for the update. Looking forward to seeing the new version.

**Comment by lukelbd** [comment] 2021-08-18 18:49
I've made some *major* changes to the internals for a v0.8 release, including improvements on the tight layout algorithm. Might be worth trying this again. Haven't been able to reproduce this since the changes

**Comment by lukelbd** [comment] 2022-01-24 03:57
I think I'll close this for now, but if anyone reading this thread experiences issues with the qt backend, please let me know and I'll be happy to reopen.

**Closed by lukelbd** 2022-01-24 03:57 UTC
Labels: bug
