### ISSUE TITLE
Set orientation to horizontal for indicate_error

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#229] opened 2020-10-04 07:13 UTC
### Description

The `indicate_error` use `fill_between` as default. How to use `fill_betweenx`?
Although I found the source of `fill_betweenx` in the source code, I tried to add `orientation='horizontal'` and got this error:
```
'Line2D' object has no property 'orientation'
```

### Steps to reproduce

```python
import numpy as np
import xarray as xr
import pandas as pd
import proplot as plot

da = xr.DataArray(
    np.random.rand(5, 4, 3, 2),
    [
        ("time", pd.date_range("2000-01-01", periods=5)),
        ("z", [0, 1, 2, 3]),
        ("y", [4, 5, 6]),
        ("x", [12, 13]),
    ],
)


f, axs = plot.subplots()
medians = da.median(['time', 'y', 'x'])


shadedata = da.quantile([0.25, 0.75], dim=['time', 'y', 'x'])
fadedata = da.quantile([0.05, 0.95], dim=['time', 'y', 'x'])

axs.plot(
    medians,
    shadedata=shadedata, fadedata=fadedata,
    shadelabel='50% CI', fadelabel='90% CI',
    color='ocean blue', barzorder=0, boxmarker=False, legend='ll',
)
```

**Expected behavior**:

Shades area is two x-axis values for one y-axis value (`fill_betweenx`).

**Actual behavior**:
`z` is the x-axis label instead of the values.

### Proplot version

0.6.4

**Comment by lukelbd** [comment] 2021-06-30 12:33
This appears to be a duplicate of: #194. Will try to address soon

**Closed by lukelbd** 2021-06-30 12:33 UTC
