### ISSUE TITLE
Overlapped alternate/twin axes

### ISSUE THREAD

**Issue by zxdawn** [lukelbd/proplot#273] opened 2021-09-01 03:05 UTC
### Description

When there're more than one alternate/twin axes, they would overlap together.

### Steps to reproduce

```python
import proplot as pplt

fig, axs = pplt.subplots(share=0)

ox1 = axs.altx(color='r', label='alternate 1')
ox2 = axs.altx(color='b', label='alternate 2')
```

**Expected behavior**:
The spaces between axes should be adjusted autoamtically.
![image](https://user-images.githubusercontent.com/30388627/131604980-370147c6-8e0b-4a73-bc41-c888ed0bc04d.png)

**Actual behavior**:
![image](https://user-images.githubusercontent.com/30388627/131604826-33769b23-4729-4f87-bf7a-70dd3a76572d.png)

### Manual fixes

```python
import proplot as pplt

fig, axs = pplt.subplots(share=0)

ox1 = axs.altx(color='r', label='alternate 1')
ox2 = axs.altx(color='b', label='alternate 2')
ox2.spines["top"].set_position(("axes", 1.2))
```

### Proplot version

matplotlib 3.3.4
proplot 0.8.1

**Comment by lukelbd** [comment] 2021-09-08 19:11
I think this is a duplicate of #51. Definitely on the to-do list

**Closed by lukelbd** 2021-09-08 19:11 UTC
